mixed-port: 7890
ipv6: false
allow-lan: true
mode: rule
log-level: warning
unified-delay: false
tcp-concurrent: true
geo-auto-update: true
geo-update-interval: 168
external-controller: 127.0.0.1:9090
external-controller-cors:
  allow-origins:
  - '*'
  allow-private-network: true
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  respect-rules: true
  use-system-hosts: false
  listen: 0.0.0.0:1053
  ipv6: false
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
  proxy-server-nameserver:
  - 8.8.8.8
  direct-nameserver:
  - 8.8.8.8
  direct-nameserver-follow-policy: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - '*.localhost'
  - '*.ir'
  - '*.test'
  - '*.localdomain'
  - '*.home'
  - '*.internal'
tun:
  enable: true
  stack: gvisor
  auto-route: true
  strict-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
  mtu: 9000
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports:
      - 80
      - 8080
      - 8880
      - 2052
      - 2082
      - 2086
      - 2095
    TLS:
      ports:
      - 443
      - 8443
      - 2053
      - 2083
      - 2087
      - 2096
proxies:
- name: 'ARISTA🔥 #1'
  type: ss
  server: 185.226.119.96
  port: 8082
  cipher: chacha20-ietf-poly1305
  password: eI-mHmYodzH2aGXorqp8pA
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #2'
  type: ss
  server: 149.102.152.25
  port: 80
  cipher: aes-256-gcm
  password: RLUoaU4nh8b8Mqq7
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #3'
  type: ss
  server: 203.32.26.24
  port: 60981
  cipher: aes-256-gcm
  password: 63d7c17506d1f48b
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #4'
  type: ss
  server: 108.181.0.177
  port: 8388
  cipher: chacha20-ietf-poly1305
  password: G5p6ww4o67HB
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #5'
  type: ss
  server: 71.19.148.74
  port: 443
  cipher: chacha20-ietf-poly1305
  password: gqkUCvmeOTghYJXF1YIuk5
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #6'
  type: ss
  server: 95.173.218.203
  port: 990
  cipher: chacha20-ietf-poly1305
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #7'
  type: ss
  server: 31.220.61.82
  port: 17040
  cipher: aes-256-gcm
  password: xCQlhRy7oxS3FHYH8qtUjpSGt2XPwxEDiRrXY/XObvk=
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #8'
  type: ss
  server: 168.144.39.249
  port: 29122
  cipher: aes-256-gcm
  password: Sd8+BcR1qxc75ZHEGp5r8sJR+woKRY+z6AYqNfWc48U=
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #9'
  type: ss
  server: 92.118.112.203
  port: 41348
  cipher: chacha20-ietf-poly1305
  password: 66iAPUHyyA3YxBb3DmloTuArM0IiPeY2HCoH3m
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #10'
  type: ss
  server: 114.45.177.19
  port: 50099
  cipher: chacha20-ietf-poly1305
  password: 7e731ec3-f8e1-43f6-92cf-3978d14705c4
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #11'
  type: ss
  server: 193.29.139.179
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: cvII85TrW6n0OGyfpHVS1u
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #12'
  type: ss
  server: 103.106.228.177
  port: 31348
  cipher: chacha20-ietf-poly1305
  password: WTZvNByN7m2ZAlp0B1YVCQdaehZsfnSL33hBOZWsZDDjN0GK
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #13'
  type: ss
  server: 8.209.74.72
  port: 20001
  cipher: chacha20-ietf-poly1305
  password: PWpjPo3tqhPN4yRZ
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #14'
  type: ss
  server: 47.79.144.115
  port: 40003
  cipher: aes-256-gcm
  password: GTZI5AbjNAeWQG0oVNptvWJogHNKiiKA
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #15'
  type: ss
  server: 195.133.2.2
  port: 34898
  cipher: chacha20-ietf-poly1305
  password: RbIsi7QmpwbYYG9CbN40BS
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #16'
  type: ss
  server: 147.78.0.182
  port: 990
  cipher: chacha20-ietf-poly1305
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  udp: true
  tcp-fast-open: true
proxy-groups:
- name: Proxy Select
  type: select
  proxies:
  - Auto Select
  - 'ARISTA🔥 #1'
  - 'ARISTA🔥 #2'
  - 'ARISTA🔥 #3'
  - 'ARISTA🔥 #4'
  - 'ARISTA🔥 #5'
  - 'ARISTA🔥 #6'
  - 'ARISTA🔥 #7'
  - 'ARISTA🔥 #8'
  - 'ARISTA🔥 #9'
  - 'ARISTA🔥 #10'
  - 'ARISTA🔥 #11'
  - 'ARISTA🔥 #12'
  - 'ARISTA🔥 #13'
  - 'ARISTA🔥 #14'
  - 'ARISTA🔥 #15'
  - 'ARISTA🔥 #16'
  - DIRECT
- name: Auto Select
  type: url-test
  proxies:
  - 'ARISTA🔥 #1'
  - 'ARISTA🔥 #2'
  - 'ARISTA🔥 #3'
  - 'ARISTA🔥 #4'
  - 'ARISTA🔥 #5'
  - 'ARISTA🔥 #6'
  - 'ARISTA🔥 #7'
  - 'ARISTA🔥 #8'
  - 'ARISTA🔥 #9'
  - 'ARISTA🔥 #10'
  - 'ARISTA🔥 #11'
  - 'ARISTA🔥 #12'
  - 'ARISTA🔥 #13'
  - 'ARISTA🔥 #14'
  - 'ARISTA🔥 #15'
  - 'ARISTA🔥 #16'
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 150
  lazy: true
rules:
- DOMAIN-SUFFIX,net2025.afsharidempire.uk,DIRECT
- DOMAIN,cp.cloudflare.com,Auto Select
- DOMAIN-SUFFIX,cdn.ir,DIRECT
- DOMAIN-SUFFIX,aparat.com,DIRECT
- DOMAIN-SUFFIX,digikala.com,DIRECT
- DOMAIN-SUFFIX,divar.ir,DIRECT
- DOMAIN-SUFFIX,snapp.ir,DIRECT
- DOMAIN-SUFFIX,torob.com,DIRECT
- DOMAIN-SUFFIX,bamilo.com,DIRECT
- DOMAIN-SUFFIX,alibaba.ir,DIRECT
- DOMAIN-SUFFIX,ban.ir,DIRECT
- DOMAIN-KEYWORD,telegram,Auto Select
- DOMAIN-SUFFIX,t.me,Auto Select
- DOMAIN-SUFFIX,telegram.org,Auto Select
- DOMAIN-SUFFIX,google.com,Auto Select
- DOMAIN-SUFFIX,youtube.com,Auto Select
- DOMAIN-SUFFIX,github.com,Auto Select
- DOMAIN-SUFFIX,instagram.com,Auto Select
- DOMAIN-SUFFIX,twitter.com,Auto Select
- DOMAIN-SUFFIX,whatsapp.com,Auto Select
- GEOIP,IR,DIRECT
- MATCH,Proxy Select
ntp:
  enable: true
  server: time.cloudflare.com
  port: 123
  interval: 30
