mixed-port: 7890
ipv6: false
allow-lan: true
mode: rule
log-level: warning
unified-delay: false
tcp-concurrent: true
geo-auto-update: true
geo-update-interval: 168
external-controller: 127.0.0.1:9090
external-controller-cors:
  allow-origins:
  - '*'
  allow-private-network: true
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  respect-rules: true
  use-system-hosts: false
  listen: 0.0.0.0:1053
  ipv6: false
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
  proxy-server-nameserver:
  - 8.8.8.8
  direct-nameserver:
  - 8.8.8.8
  direct-nameserver-follow-policy: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - '*.localhost'
  - '*.ir'
  - '*.test'
  - '*.localdomain'
  - '*.home'
  - '*.internal'
tun:
  enable: true
  stack: gvisor
  auto-route: true
  strict-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
  mtu: 9000
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports:
      - 80
      - 8080
      - 8880
      - 2052
      - 2082
      - 2086
      - 2095
    TLS:
      ports:
      - 443
      - 8443
      - 2053
      - 2083
      - 2087
      - 2096
proxies:
- name: 'ARISTA #1'
  type: ss
  server: admin.c1.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: W74XFALLLuw6m5IA
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #2'
  type: ss
  server: uk1.connectsuite.org
  port: 2083
  cipher: aes-256-gcm
  password: f4e7cc3b-1fde-4861-9a7e-294728d8a16a
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #3'
  type: ss
  server: series-a1.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: W74XFALLLuw6m5IA
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #4'
  type: ss
  server: series-a2.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: W74XFALLLuw6m5IA
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #5'
  type: ss
  server: 188.121.123.189
  port: 4050
  cipher: chacha20-ietf-poly1305
  password: cjLCeA1Nk4KGpSdZEVxWjg7nETc3FJ_g
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #6'
  type: ss
  server: 85.133.215.4
  port: 42152
  cipher: chacha20-ietf-poly1305
  password: woXDpsOxL8KEwrhjwobCplcHdw3CicKrEEFWw6ANwovCsl5xP8OPw4LCkcOaw5nDuVw=
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #7'
  type: ss
  server: 82.38.31.185
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: k1dBOmOB4oqi7Ump37a1bQ
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #8'
  type: ss
  server: admin.c1.havij.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1kVr0KATIJI7mwOF
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #9'
  type: ss
  server: 95.38.186.24
  port: 10129
  cipher: aes-256-gcm
  password: MjE3NDZmZGYxMmYxOWNhODdjMThjYWMyYWIwOTIw
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #10'
  type: ss
  server: 82.38.31.218
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: k1dBOmOB4oqi7Ump37a1bQ
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #11'
  type: ss
  server: 82.38.31.208
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: k1dBOmOB4oqi7Ump37a1bQ
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #12'
  type: ss
  server: 62.133.63.169
  port: 37096
  cipher: chacha20-ietf-poly1305
  password: KP6FQVmJhlXPgvPhrw2gnI
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #13'
  type: ss
  server: 108.181.58.239
  port: 8388
  cipher: chacha20-ietf-poly1305
  password: CJmTCCx7Ltud
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #14'
  type: ss
  server: 82.38.31.176
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: k1dBOmOB4oqi7Ump37a1bQ
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #15'
  type: ss
  server: 81.19.141.45
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 3TnQdgm2mVJQbuSCXmR5Vc
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #16'
  type: ss
  server: 85.192.49.179
  port: 51523
  cipher: chacha20-ietf-poly1305
  password: ABoEpxeU9FbQr7_Jn7KU4sUqD7RKjBs2
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #17'
  type: ss
  server: 36.230.60.182
  port: 50099
  cipher: chacha20-ietf-poly1305
  password: 7e731ec3-f8e1-43f6-92cf-3978d14705c4
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #18'
  type: ss
  server: 193.29.139.227
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: fbx1Fw7mENCd7vZMvorQZ5
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #19'
  type: ss
  server: 107.172.250.161
  port: 59556
  cipher: chacha20-ietf-poly1305
  password: QTmLViU4VEmuwbOxUw4IXd
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #20'
  type: ss
  server: 193.29.139.179
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: cvII85TrW6n0OGyfpHVS1u
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #21'
  type: ss
  server: 109.107.182.229
  port: 51544
  cipher: chacha20-ietf-poly1305
  password: Ca4cxMttEzzRFSLpz3IcBF
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #22'
  type: ss
  server: 57.129.129.247
  port: 29757
  cipher: chacha20-ietf-poly1305
  password: 82f3a83f1556c0e3
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #23'
  type: ss
  server: 135.125.219.2
  port: 23349
  cipher: chacha20-ietf-poly1305
  password: 0b2e39a4642684aa
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #24'
  type: ss
  server: 168.138.175.92
  port: 9888
  cipher: aes-128-gcm
  password: JVSuuib4ydvY8m7u6jElTYbeRO8ygJ4Hi8Iq733BqAkF
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #25'
  type: ss
  server: 94.131.127.154
  port: 48877
  cipher: chacha20-ietf-poly1305
  password: VZNRwzYN2qGsP7jqTdvpq5k6j3g7hU2dbM4Lkd3n9Uox324inf6PPUih2Qo9wfXEoGNCBhdDsrVutLmmvUZihMsmsuGpMu7R
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #26'
  type: ss
  server: 193.29.139.164
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: 1RWwXhwfAB5gAEozU4G2Pg
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #27'
  type: ss
  server: 130.49.161.18
  port: 28474
  cipher: chacha20-ietf-poly1305
  password: _TusuE5i0EzyvWsQuTiKMMr_j_sduu2E
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #28'
  type: ss
  server: 1.170.211.11
  port: 38320
  cipher: chacha20-ietf-poly1305
  password: a5115845-cc23-4082-905e-869fe212dfef
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #29'
  type: ss
  server: 1.170.211.11
  port: 36321
  cipher: chacha20-ietf-poly1305
  password: a5115845-cc23-4082-905e-869fe212dfef
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #30'
  type: ss
  server: 5.34.177.228
  port: 41348
  cipher: chacha20-ietf-poly1305
  password: vJ4LrBqkqCYgGMO08YmmsMjQ3ZMtJ7Ey6Sxfpe
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #31'
  type: ss
  server: 94.131.127.154
  port: 48877
  cipher: chacha20-ietf-poly1305
  password: VZNRwzYN2qGsP7jqTdvpq5k6j3g7hU2dbM4Lkd3n9Uox324inf6PPUih2Qo9wfXEoGNCBhdDsrVutLmmvUZihMsmsuGpMu7R
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #32'
  type: ss
  server: 188.213.197.64
  port: 13641
  cipher: chacha20-ietf-poly1305
  password: IkaP6wJClOqW+3hSnkz5dHc7nve52fRdMbJY1TqfphM=
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #33'
  type: ss
  server: 185.231.183.161
  port: 51570
  cipher: chacha20-ietf-poly1305
  password: CA/X/X0t+T2niaTfeCxR87InoJ94YvPQBLiyPQogKvA=
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #34'
  type: ss
  server: 94.198.220.183
  port: 64674
  cipher: chacha20-ietf-poly1305
  password: s8LbJCgUiGXeCKVc63tHJP
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #35'
  type: ss
  server: 193.233.18.234
  port: 443
  cipher: chacha20-ietf-poly1305
  password: YvNtVuLvHpZVAr8RMVRWRb
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #36'
  type: ss
  server: 115.161.136.145
  port: 10099
  cipher: chacha20-ietf-poly1305
  password: '12242'
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #37'
  type: ss
  server: ru.moktana.app
  port: 51523
  cipher: chacha20-ietf-poly1305
  password: 7SEstdmLhf-aFK_G9eaYHKT_YpSov58B
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #38'
  type: ss
  server: 90.156.203.62
  port: 5112
  cipher: chacha20-ietf-poly1305
  password: VVlAff77CnAU43Aoc5j15Y
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #39'
  type: ss
  server: 193.29.139.143
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 1RWwXhwfAB5gAEozU4G2Pg
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #40'
  type: ss
  server: 65.109.176.194
  port: 2053
  cipher: aes-128-gcm
  password: '@V2RayyNGvpn'
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #41'
  type: ss
  server: 108.181.58.239
  port: 8388
  cipher: chacha20-ietf-poly1305
  password: CJmTCCx7Ltud
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #42'
  type: ss
  server: 38.135.24.131
  port: 443
  cipher: chacha20-ietf-poly1305
  password: hbGrpfvNrJsUmKmPbR3iY2
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #44'
  type: ss
  server: 77.90.60.136
  port: 990
  cipher: chacha20-ietf-poly1305
  password: nodes-37411c3e
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #45'
  type: ss
  server: 195.93.253.240
  port: 14130
  cipher: chacha20-ietf-poly1305
  password: zfRwdreLaBOGwUzCaWmvIN
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #46'
  type: ss
  server: 195.93.253.245
  port: 49137
  cipher: chacha20-ietf-poly1305
  password: FDeCHSu4lt8qflCS5zDOy8
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #48'
  type: ss
  server: 38.135.24.131
  port: 443
  cipher: chacha20-ietf-poly1305
  password: hbGrpfvNrJsUmKmPbR3iY2
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #49'
  type: ss
  server: 103.186.154.208
  port: 38388
  cipher: aes-256-cfb
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #50'
  type: ss
  server: 185.189.160.105
  port: 41632
  cipher: aes-256-cfb
  password: qwerREWQ@@
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #51'
  type: ss
  server: 16.52.154.170
  port: 443
  cipher: aes-256-cfb
  password: amazonskr05
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #52'
  type: ss
  server: 82.38.31.155
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: oZIoA69Q8yhcQV8ka3Pa3A
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #53'
  type: ss
  server: 15.223.186.62
  port: 443
  cipher: aes-256-cfb
  password: amazonskr05
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #54'
  type: ss
  server: 35.182.57.53
  port: 443
  cipher: aes-256-cfb
  password: amazonskr05
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #55'
  type: ss
  server: 82.38.31.205
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: k1dBOmOB4oqi7Ump37a1bQ
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #56'
  type: ss
  server: 221.139.79.57
  port: 13979
  cipher: aes-256-cfb
  password: qwerREWQ@@
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #57'
  type: ss
  server: 52.60.99.199
  port: 443
  cipher: aes-256-cfb
  password: amazonskr05
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #58'
  type: ss
  server: 3.96.152.83
  port: 443
  cipher: aes-256-cfb
  password: amazonskr05
  udp: true
  tcp-fast-open: true
- name: 'ARISTA #59'
  type: ss
  server: 82.38.31.214
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: k1dBOmOB4oqi7Ump37a1bQ
  udp: true
  tcp-fast-open: true
proxy-groups:
- name: Proxy Select
  type: select
  proxies:
  - Auto Select
  - 'ARISTA #1'
  - 'ARISTA #2'
  - 'ARISTA #3'
  - 'ARISTA #4'
  - 'ARISTA #5'
  - 'ARISTA #6'
  - 'ARISTA #7'
  - 'ARISTA #8'
  - 'ARISTA #9'
  - 'ARISTA #10'
  - 'ARISTA #11'
  - 'ARISTA #12'
  - 'ARISTA #13'
  - 'ARISTA #14'
  - 'ARISTA #15'
  - 'ARISTA #16'
  - 'ARISTA #17'
  - 'ARISTA #18'
  - 'ARISTA #19'
  - 'ARISTA #20'
  - 'ARISTA #21'
  - 'ARISTA #22'
  - 'ARISTA #23'
  - 'ARISTA #24'
  - 'ARISTA #25'
  - 'ARISTA #26'
  - 'ARISTA #27'
  - 'ARISTA #28'
  - 'ARISTA #29'
  - 'ARISTA #30'
  - 'ARISTA #31'
  - 'ARISTA #32'
  - 'ARISTA #33'
  - 'ARISTA #34'
  - 'ARISTA #35'
  - 'ARISTA #36'
  - 'ARISTA #37'
  - 'ARISTA #38'
  - 'ARISTA #39'
  - 'ARISTA #40'
  - 'ARISTA #41'
  - 'ARISTA #42'
  - 'ARISTA #44'
  - 'ARISTA #45'
  - 'ARISTA #46'
  - 'ARISTA #48'
  - 'ARISTA #49'
  - 'ARISTA #50'
  - 'ARISTA #51'
  - 'ARISTA #52'
  - 'ARISTA #53'
  - 'ARISTA #54'
  - 'ARISTA #55'
  - 'ARISTA #56'
  - 'ARISTA #57'
  - 'ARISTA #58'
  - 'ARISTA #59'
  - DIRECT
- name: Auto Select
  type: url-test
  proxies:
  - 'ARISTA #1'
  - 'ARISTA #2'
  - 'ARISTA #3'
  - 'ARISTA #4'
  - 'ARISTA #5'
  - 'ARISTA #6'
  - 'ARISTA #7'
  - 'ARISTA #8'
  - 'ARISTA #9'
  - 'ARISTA #10'
  - 'ARISTA #11'
  - 'ARISTA #12'
  - 'ARISTA #13'
  - 'ARISTA #14'
  - 'ARISTA #15'
  - 'ARISTA #16'
  - 'ARISTA #17'
  - 'ARISTA #18'
  - 'ARISTA #19'
  - 'ARISTA #20'
  - 'ARISTA #21'
  - 'ARISTA #22'
  - 'ARISTA #23'
  - 'ARISTA #24'
  - 'ARISTA #25'
  - 'ARISTA #26'
  - 'ARISTA #27'
  - 'ARISTA #28'
  - 'ARISTA #29'
  - 'ARISTA #30'
  - 'ARISTA #31'
  - 'ARISTA #32'
  - 'ARISTA #33'
  - 'ARISTA #34'
  - 'ARISTA #35'
  - 'ARISTA #36'
  - 'ARISTA #37'
  - 'ARISTA #38'
  - 'ARISTA #39'
  - 'ARISTA #40'
  - 'ARISTA #41'
  - 'ARISTA #42'
  - 'ARISTA #44'
  - 'ARISTA #45'
  - 'ARISTA #46'
  - 'ARISTA #48'
  - 'ARISTA #49'
  - 'ARISTA #50'
  - 'ARISTA #51'
  - 'ARISTA #52'
  - 'ARISTA #53'
  - 'ARISTA #54'
  - 'ARISTA #55'
  - 'ARISTA #56'
  - 'ARISTA #57'
  - 'ARISTA #58'
  - 'ARISTA #59'
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 150
  lazy: true
rules:
- DOMAIN-SUFFIX,net2025.afsharidempire.uk,DIRECT
- DOMAIN,cp.cloudflare.com,Auto Select
- DOMAIN-SUFFIX,cdn.ir,DIRECT
- DOMAIN-SUFFIX,aparat.com,DIRECT
- DOMAIN-SUFFIX,digikala.com,DIRECT
- DOMAIN-SUFFIX,divar.ir,DIRECT
- DOMAIN-SUFFIX,snapp.ir,DIRECT
- DOMAIN-SUFFIX,torob.com,DIRECT
- DOMAIN-SUFFIX,bamilo.com,DIRECT
- DOMAIN-SUFFIX,alibaba.ir,DIRECT
- DOMAIN-SUFFIX,ban.ir,DIRECT
- DOMAIN-KEYWORD,telegram,Auto Select
- DOMAIN-SUFFIX,t.me,Auto Select
- DOMAIN-SUFFIX,telegram.org,Auto Select
- DOMAIN-SUFFIX,google.com,Auto Select
- DOMAIN-SUFFIX,youtube.com,Auto Select
- DOMAIN-SUFFIX,github.com,Auto Select
- DOMAIN-SUFFIX,instagram.com,Auto Select
- DOMAIN-SUFFIX,twitter.com,Auto Select
- DOMAIN-SUFFIX,whatsapp.com,Auto Select
- GEOIP,IR,DIRECT
- MATCH,Proxy Select
ntp:
  enable: true
  server: time.cloudflare.com
  port: 123
  interval: 30
