mixed-port: 7890
ipv6: false
allow-lan: true
mode: rule
log-level: warning
unified-delay: false
tcp-concurrent: true
geo-auto-update: true
geo-update-interval: 168
external-controller: 127.0.0.1:9090
external-controller-cors:
  allow-origins:
  - '*'
  allow-private-network: true
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  respect-rules: true
  use-system-hosts: false
  listen: 0.0.0.0:1053
  ipv6: false
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
  proxy-server-nameserver:
  - 8.8.8.8
  direct-nameserver:
  - 8.8.8.8
  direct-nameserver-follow-policy: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - '*.localhost'
  - '*.ir'
  - '*.test'
  - '*.localdomain'
  - '*.home'
  - '*.internal'
tun:
  enable: true
  stack: gvisor
  auto-route: true
  strict-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
  mtu: 9000
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports:
      - 80
      - 8080
      - 8880
      - 2052
      - 2082
      - 2086
      - 2095
    TLS:
      ports:
      - 443
      - 8443
      - 2053
      - 2083
      - 2087
      - 2096
proxies:
- name: 'ARISTA🔥 #1'
  type: ss
  server: 51.241.20.195
  port: 443
  cipher: chacha20-ietf-poly1305
  password: ImklcJyi52glFmSRoVko7K
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #2'
  type: ss
  server: 109.122.196.106
  port: 443
  cipher: chacha20-ietf-poly1305
  password: w3JDLilehmBXnpPZp8Mcrj
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #3'
  type: ss
  server: 111.248.76.47
  port: 50099
  cipher: chacha20-ietf-poly1305
  password: 7e731ec3-f8e1-43f6-92cf-3978d14705c4
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #4'
  type: ss
  server: 72.56.235.141
  port: 8388
  cipher: chacha20-ietf-poly1305
  password: X6btbRvJCo3uTQ--yaaT8Mvh0CgqhYTL
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #5'
  type: ss
  server: 149.28.255.6
  port: 816
  cipher: chacha20-ietf-poly1305
  password: GyZ5Xo0ht41vYmW3H4
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #6'
  type: ss
  server: 193.29.139.202
  port: 8080
  cipher: chacha20-ietf-poly1305
  password: oZIoA69Q8yhcQV8ka3Pa3A
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #7'
  type: ss
  server: 104.192.227.162
  port: 443
  cipher: chacha20-ietf-poly1305
  password: 91LFVJhY6a7f8KeJPeuYln
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #8'
  type: ss
  server: 107.172.250.161
  port: 59556
  cipher: chacha20-ietf-poly1305
  password: QTmLViU4VEmuwbOxUw4IXd
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #9'
  type: ss
  server: 150.241.72.79
  port: 8388
  cipher: chacha20-ietf-poly1305
  password: X6btbRvJCo3uTQ--yaaT8Mvh0CgqhYTL
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #10'
  type: ss
  server: 94.72.127.58
  port: 443
  cipher: aes-256-gcm
  password: jJHq807bQ7TM0yOh
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #11'
  type: ss
  server: 154.18.239.126
  port: 37425
  cipher: chacha20-ietf-poly1305
  password: eLPlIVuRZ6UJyapVDeT++l7fYC0uowXJFlb9qhntAd4=
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #12'
  type: ss
  server: 109.176.229.55
  port: 8388
  cipher: chacha20-ietf-poly1305
  password: X6btbRvJCo3uTQ--yaaT8Mvh0CgqhYTL
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #14'
  type: ss
  server: 38.180.152.210
  port: 8881
  cipher: aes-256-gcm
  password: kDWvXYZoTBcGkC4
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #15'
  type: ss
  server: 138.186.142.80
  port: 990
  cipher: chacha20-ietf-poly1305
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  udp: true
  tcp-fast-open: true
- name: 'ARISTA🔥 #16'
  type: ss
  server: 80.71.152.33
  port: 8388
  cipher: chacha20-ietf-poly1305
  password: X6btbRvJCo3uTQ--yaaT8Mvh0CgqhYTL
  udp: true
  tcp-fast-open: true
proxy-groups:
- name: Proxy Select
  type: select
  proxies:
  - Auto Select
  - 'ARISTA🔥 #1'
  - 'ARISTA🔥 #2'
  - 'ARISTA🔥 #3'
  - 'ARISTA🔥 #4'
  - 'ARISTA🔥 #5'
  - 'ARISTA🔥 #6'
  - 'ARISTA🔥 #7'
  - 'ARISTA🔥 #8'
  - 'ARISTA🔥 #9'
  - 'ARISTA🔥 #10'
  - 'ARISTA🔥 #11'
  - 'ARISTA🔥 #12'
  - 'ARISTA🔥 #14'
  - 'ARISTA🔥 #15'
  - 'ARISTA🔥 #16'
  - DIRECT
- name: Auto Select
  type: url-test
  proxies:
  - 'ARISTA🔥 #1'
  - 'ARISTA🔥 #2'
  - 'ARISTA🔥 #3'
  - 'ARISTA🔥 #4'
  - 'ARISTA🔥 #5'
  - 'ARISTA🔥 #6'
  - 'ARISTA🔥 #7'
  - 'ARISTA🔥 #8'
  - 'ARISTA🔥 #9'
  - 'ARISTA🔥 #10'
  - 'ARISTA🔥 #11'
  - 'ARISTA🔥 #12'
  - 'ARISTA🔥 #14'
  - 'ARISTA🔥 #15'
  - 'ARISTA🔥 #16'
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 150
  lazy: true
rules:
- DOMAIN-SUFFIX,net2025.afsharidempire.uk,DIRECT
- DOMAIN,cp.cloudflare.com,Auto Select
- DOMAIN-SUFFIX,cdn.ir,DIRECT
- DOMAIN-SUFFIX,aparat.com,DIRECT
- DOMAIN-SUFFIX,digikala.com,DIRECT
- DOMAIN-SUFFIX,divar.ir,DIRECT
- DOMAIN-SUFFIX,snapp.ir,DIRECT
- DOMAIN-SUFFIX,torob.com,DIRECT
- DOMAIN-SUFFIX,bamilo.com,DIRECT
- DOMAIN-SUFFIX,alibaba.ir,DIRECT
- DOMAIN-SUFFIX,ban.ir,DIRECT
- DOMAIN-KEYWORD,telegram,Auto Select
- DOMAIN-SUFFIX,t.me,Auto Select
- DOMAIN-SUFFIX,telegram.org,Auto Select
- DOMAIN-SUFFIX,google.com,Auto Select
- DOMAIN-SUFFIX,youtube.com,Auto Select
- DOMAIN-SUFFIX,github.com,Auto Select
- DOMAIN-SUFFIX,instagram.com,Auto Select
- DOMAIN-SUFFIX,twitter.com,Auto Select
- DOMAIN-SUFFIX,whatsapp.com,Auto Select
- GEOIP,IR,DIRECT
- MATCH,Proxy Select
ntp:
  enable: true
  server: time.cloudflare.com
  port: 123
  interval: 30
