mixed-port: 7890
ipv6: false
allow-lan: true
mode: rule
log-level: warning
unified-delay: false
tcp-concurrent: true
geo-auto-update: true
geo-update-interval: 168
external-controller: 127.0.0.1:9090
external-controller-cors:
  allow-origins:
  - '*'
  allow-private-network: true
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  respect-rules: true
  use-system-hosts: false
  listen: 0.0.0.0:1053
  ipv6: false
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
  proxy-server-nameserver:
  - 8.8.8.8
  direct-nameserver:
  - 8.8.8.8
  direct-nameserver-follow-policy: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - '*.localhost'
  - '*.ir'
  - '*.test'
  - '*.localdomain'
  - '*.home'
  - '*.internal'
tun:
  enable: true
  stack: gvisor
  auto-route: true
  strict-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
  mtu: 9000
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports:
      - 80
      - 8080
      - 8880
      - 2052
      - 2082
      - 2086
      - 2095
    TLS:
      ports:
      - 443
      - 8443
      - 2053
      - 2083
      - 2087
      - 2096
proxies:
- name: 'Trojan #1'
  type: trojan
  server: 216.24.57.6
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.creationlong.org
  client-fingerprint: chrome
  alpn:
  - http/1.1
  ws-opts:
    path: /assignment
    headers:
      Host: www.creationlong.org
- name: 'Trojan #2'
  type: trojan
  server: 216.24.57.6
  port: 443
  password: mitivpn
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.ir-sub.ir
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: www.ir-sub.ir
- name: 'Trojan #3'
  type: trojan
  server: 208.103.161.33
  port: 443
  password: mitivpn
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: ir-sub.ir
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: ir-sub.ir
- name: 'Trojan #4'
  type: trojan
  server: 172.238.120.124
  port: 443
  password: r-_YbwF.j0TtHVewoFIppramjAnmSfqYzJ
  network: tcp
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 172.238.120.124
  client-fingerprint: chrome
- name: 'Trojan #5'
  type: trojan
  server: 141.193.213.21
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.calmloud.com
  client-fingerprint: chrome
  alpn:
  - http/1.1
  ws-opts:
    path: /assignment
    headers:
      Host: www.calmloud.com
- name: 'Trojan #6'
  type: trojan
  server: 45.130.125.76
  port: 443
  password: Mitivpn
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: panel.hitgram.ir
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
  ws-opts:
    path: /?ed=mitivpn
    headers:
      Host: panel.hitgram.ir
- name: 'Trojan #7'
  type: trojan
  server: 45.130.125.76
  port: 443
  password: jAck1mS8h3
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: de.aananas.ir
  client-fingerprint: chrome
  alpn:
  - http/1.1
  ws-opts:
    path: /?ed=2048
    headers:
      Host: de.aananas.ir
- name: 'Trojan #8'
  type: trojan
  server: 104.18.13.149
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.calmloud.com
  client-fingerprint: ios
  ws-opts:
    path: /assignment
    headers:
      Host: www.calmloud.com
- name: 'Trojan #9'
  type: trojan
  server: 104.18.7.147
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.creationlong.org
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
  ws-opts:
    path: /assignment
    headers:
      Host: www.creationlong.org
- name: 'Trojan #10'
  type: trojan
  server: 2.144.2.51
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.ignitelimit.com
  client-fingerprint: random
  alpn:
  - h2
  ws-opts:
    path: /assignment
    headers:
      Host: www.ignitelimit.com
- name: 'Trojan #11'
  type: trojan
  server: 104.18.0.55
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.gossipglove.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.gossipglove.com
- name: 'Trojan #12'
  type: trojan
  server: 172.64.152.23
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.multiplydose.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.multiplydose.com
- name: 'Trojan #13'
  type: trojan
  server: www.gossipglove.com
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.gossipglove.com
  client-fingerprint: chrome
  alpn:
  - http/1.1
  ws-opts:
    path: /assignment
    headers:
      Host: www.gossipglove.com
- name: 'Trojan #14'
  type: trojan
  server: 188.114.97.6
  port: 443
  password: mitivpn
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: mitivpn.ws-ws-ws.workers.dev
  client-fingerprint: edge
  alpn:
  - http/1.1
  ws-opts:
    path: /720f09dba195249b423f771661162528/workers/services/view/mitivpn/production/settings
    headers:
      Host: mitivpn.ws-ws-ws.workers.dev
- name: 'Trojan #15'
  type: trojan
  server: 104.17.121.71
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.calmlunch.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.calmlunch.com
- name: 'Trojan #16'
  type: trojan
  server: 216.24.57.7
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.ignitelimit.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.ignitelimit.com
- name: 'Trojan #17'
  type: trojan
  server: 81.255.155.10
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.creationlong.org
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.creationlong.org
- name: 'Trojan #18'
  type: trojan
  server: 104.18.23.63
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.ignitelimit.com
  client-fingerprint: chrome
  alpn:
  - http/1.1
  ws-opts:
    path: /assignment
    headers:
      Host: www.ignitelimit.com
- name: 'Trojan #19'
  type: trojan
  server: 193.124.46.134
  port: 8441
  password: tunnel-astrovpn_official
  network: tcp
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: zula.ir.AstroVPN-official.AstroVPN-official.workers.dev.AstroVPN_Official.org.AstroVPN.com.AstroVPN_Official.xyz.AstroVPN_Official.AstroVPN_Official.AstroVPN_Official.AstroVPN_Official.AstroVPN_Official.AstroVPN_Official.AstroVPN_Official.AstroVPN_Official.monster.AstroVPN_OfficialJoinTelegram-------------AstroVPN_Official----------Join.ir
  client-fingerprint: chrome
  alpn:
  - http/1.1
- name: 'Trojan #20'
  type: trojan
  server: 18.163.128.27
  port: 2663
  password: f6d3aa07a52dbcedcb4731029e2fb6ae
  network: tcp
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.nintendogames.net
  client-fingerprint: chrome
- name: 'Trojan #21'
  type: trojan
  server: 104.20.42.250
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.calmloud.com
  client-fingerprint: chrome
  alpn:
  - http/1.1
  ws-opts:
    path: /assignment
    headers:
      Host: www.calmloud.com
- name: 'Trojan #22'
  type: trojan
  server: 45.130.125.69
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.calmloud.com
  client-fingerprint: chrome
  alpn:
  - http/1.1
  ws-opts:
    path: /assignment
    headers:
      Host: www.calmloud.com
- name: 'Trojan #23'
  type: trojan
  server: 188.114.97.6
  port: 443
  password: mitivpn
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: mitivpn.ws-ws-ws.workers.dev
  client-fingerprint: edge
  alpn:
  - http/1.1
  ws-opts:
    path: /720f09dba195249b423f771661162528/workers/services/view/mitivpn/production/settings
    headers:
      Host: mitivpn.ws-ws-ws.workers.dev
- name: 'Trojan #24'
  type: trojan
  server: 51.44.95.202
  port: 22223
  password: telegram-id-directvpn
  network: tcp
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: trojan.burgerip.co.uk
  client-fingerprint: chrome
  alpn:
  - http/1.1
- name: 'Trojan #25'
  type: trojan
  server: 45.12.146.179
  port: 4443
  password: strong-secret-pass-777
  network: tcp
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 45.12.146.179
  client-fingerprint: chrome
- name: 'Trojan #26'
  type: trojan
  server: 15.224.25.236
  port: 22222
  password: telegram-id-privatevpns
  network: tcp
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: trojan.burgerip.co.uk
  client-fingerprint: chrome
  alpn:
  - http/1.1
- name: 'Trojan #27'
  type: trojan
  server: 165.215.250.14
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.ignitelimit.com
  client-fingerprint: chrome
  alpn:
  - http/1.1
  ws-opts:
    path: /assignment
    headers:
      Host: www.ignitelimit.com
- name: 'Trojan #28'
  type: trojan
  server: 45.79.8.17
  port: 443
  password: rXyShM8Jni%2B5Sbq3k4gkyr5Lq0zOMRL2Uf
  network: tcp
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 45.79.8.17
  client-fingerprint: chrome
- name: 'Trojan #29'
  type: trojan
  server: 13.36.249.118
  port: 22222
  password: telegram-id-privatevpns
  network: tcp
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 13.36.249.118
  client-fingerprint: chrome
- name: 'Trojan #30'
  type: trojan
  server: 172.238.19.11
  port: 443
  password: E_hUHrn0%2B6VeZO%3Dv9%3DfLgoPDXZWGfcrejg
  network: tcp
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 172.238.19.11
  client-fingerprint: chrome
- name: 'Trojan #31'
  type: trojan
  server: 104.17.121.9
  port: 443
  password: Mitivpn
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: my.hitgram.ir
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
  ws-opts:
    path: /
    headers:
      Host: my.hitgram.ir
- name: 'Trojan #32'
  type: trojan
  server: 172.238.120.124
  port: 443
  password: r-_YbwF.j0TtHVewoFIppramjAnmSfqYzJ
  network: tcp
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 172.238.120.124
  client-fingerprint: chrome
- name: 'Trojan #33'
  type: trojan
  server: 172.232.194.147
  port: 443
  password: G2qM_GHnAEpbuIp1mcZh3mGvVn3+rHrwNe
  network: tcp
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 172.232.194.147
  client-fingerprint: chrome
- name: 'Trojan #34'
  type: trojan
  server: 78.159.131.12
  port: 28259
  password: MeaDiUmPlkWbZJ2BON8tz
  network: tcp
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: ads.x5.ru
  client-fingerprint: chrome
- name: 'Trojan #35'
  type: trojan
  server: 216.24.57.7
  port: 443
  password: Mitivpn
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: cdn.hitgram.ir
  client-fingerprint: chrome
  alpn:
  - http/1.1
  ws-opts:
    path: /?ed=2048
    headers:
      Host: cdn.hitgram.ir
- name: 'Trojan #36'
  type: trojan
  server: 216.24.57.7
  port: 443
  password: Mitivpn
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.hitgram.ir
  client-fingerprint: chrome
  alpn:
  - http/1.1
  ws-opts:
    path: /?ed=2048
    headers:
      Host: www.hitgram.ir
- name: 'Trojan #37'
  type: trojan
  server: 18.166.59.84
  port: 7484
  password: BxceQaOe
  network: tcp
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: t.me%2Fripaojiedian
  client-fingerprint: chrome
- name: 'Trojan #38'
  type: trojan
  server: www.multiplydose.com
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.multiplydose.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.multiplydose.com
- name: 'Trojan #39'
  type: trojan
  server: 45.130.125.76
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.calmlunch.com
  client-fingerprint: chrome
  alpn:
  - http/1.1
  ws-opts:
    path: /assignment
    headers:
      Host: www.calmlunch.com
- name: 'Trojan #40'
  type: trojan
  server: 104.17.121.71
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.multiplydose.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.multiplydose.com
- name: 'Trojan #41'
  type: trojan
  server: 198.62.62.251
  port: 443
  password: Mitivpn
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: dash.hitgram.ir
  client-fingerprint: chrome
  alpn:
  - http/1.1
  ws-opts:
    path: /?ed=2048
    headers:
      Host: dash.hitgram.ir
- name: 'Trojan #42'
  type: trojan
  server: pokemonus-01.yunjnet.com
  port: 56115
  password: e2f70d88-8a9a-4a41-a220-9e50d8cf283d
  network: tcp
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: iosapps.itunes.apple.com
  client-fingerprint: chrome
proxy-groups:
- name: Proxy Select
  type: select
  proxies:
  - Auto Select
  - 'Trojan #1'
  - 'Trojan #2'
  - 'Trojan #3'
  - 'Trojan #4'
  - 'Trojan #5'
  - 'Trojan #6'
  - 'Trojan #7'
  - 'Trojan #8'
  - 'Trojan #9'
  - 'Trojan #10'
  - 'Trojan #11'
  - 'Trojan #12'
  - 'Trojan #13'
  - 'Trojan #14'
  - 'Trojan #15'
  - 'Trojan #16'
  - 'Trojan #17'
  - 'Trojan #18'
  - 'Trojan #19'
  - 'Trojan #20'
  - 'Trojan #21'
  - 'Trojan #22'
  - 'Trojan #23'
  - 'Trojan #24'
  - 'Trojan #25'
  - 'Trojan #26'
  - 'Trojan #27'
  - 'Trojan #28'
  - 'Trojan #29'
  - 'Trojan #30'
  - 'Trojan #31'
  - 'Trojan #32'
  - 'Trojan #33'
  - 'Trojan #34'
  - 'Trojan #35'
  - 'Trojan #36'
  - 'Trojan #37'
  - 'Trojan #38'
  - 'Trojan #39'
  - 'Trojan #40'
  - 'Trojan #41'
  - 'Trojan #42'
  - DIRECT
- name: Auto Select
  type: url-test
  proxies:
  - 'Trojan #1'
  - 'Trojan #2'
  - 'Trojan #3'
  - 'Trojan #4'
  - 'Trojan #5'
  - 'Trojan #6'
  - 'Trojan #7'
  - 'Trojan #8'
  - 'Trojan #9'
  - 'Trojan #10'
  - 'Trojan #11'
  - 'Trojan #12'
  - 'Trojan #13'
  - 'Trojan #14'
  - 'Trojan #15'
  - 'Trojan #16'
  - 'Trojan #17'
  - 'Trojan #18'
  - 'Trojan #19'
  - 'Trojan #20'
  - 'Trojan #21'
  - 'Trojan #22'
  - 'Trojan #23'
  - 'Trojan #24'
  - 'Trojan #25'
  - 'Trojan #26'
  - 'Trojan #27'
  - 'Trojan #28'
  - 'Trojan #29'
  - 'Trojan #30'
  - 'Trojan #31'
  - 'Trojan #32'
  - 'Trojan #33'
  - 'Trojan #34'
  - 'Trojan #35'
  - 'Trojan #36'
  - 'Trojan #37'
  - 'Trojan #38'
  - 'Trojan #39'
  - 'Trojan #40'
  - 'Trojan #41'
  - 'Trojan #42'
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 150
  lazy: true
rules:
- DOMAIN-SUFFIX,net2025.afsharidempire.uk,DIRECT
- DOMAIN,cp.cloudflare.com,Auto Select
- DOMAIN-SUFFIX,cdn.ir,DIRECT
- DOMAIN-SUFFIX,aparat.com,DIRECT
- DOMAIN-SUFFIX,digikala.com,DIRECT
- DOMAIN-SUFFIX,divar.ir,DIRECT
- DOMAIN-SUFFIX,snapp.ir,DIRECT
- DOMAIN-SUFFIX,torob.com,DIRECT
- DOMAIN-SUFFIX,bamilo.com,DIRECT
- DOMAIN-SUFFIX,alibaba.ir,DIRECT
- DOMAIN-SUFFIX,ban.ir,DIRECT
- DOMAIN-KEYWORD,telegram,Auto Select
- DOMAIN-SUFFIX,t.me,Auto Select
- DOMAIN-SUFFIX,telegram.org,Auto Select
- DOMAIN-SUFFIX,google.com,Auto Select
- DOMAIN-SUFFIX,youtube.com,Auto Select
- DOMAIN-SUFFIX,github.com,Auto Select
- DOMAIN-SUFFIX,instagram.com,Auto Select
- DOMAIN-SUFFIX,twitter.com,Auto Select
- DOMAIN-SUFFIX,whatsapp.com,Auto Select
- GEOIP,IR,DIRECT
- MATCH,Proxy Select
ntp:
  enable: true
  server: time.cloudflare.com
  port: 123
  interval: 30
