mixed-port: 7890
ipv6: false
allow-lan: true
mode: rule
log-level: warning
unified-delay: false
tcp-concurrent: true
geo-auto-update: true
geo-update-interval: 168
external-controller: 127.0.0.1:9090
external-controller-cors:
  allow-origins:
  - '*'
  allow-private-network: true
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  respect-rules: true
  use-system-hosts: false
  listen: 0.0.0.0:1053
  ipv6: false
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
  proxy-server-nameserver:
  - 8.8.8.8
  direct-nameserver:
  - 8.8.8.8
  direct-nameserver-follow-policy: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - '*.localhost'
  - '*.ir'
  - '*.test'
  - '*.localdomain'
  - '*.home'
  - '*.internal'
tun:
  enable: true
  stack: gvisor
  auto-route: true
  strict-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
  mtu: 9000
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports:
      - 80
      - 8080
      - 8880
      - 2052
      - 2082
      - 2086
      - 2095
    TLS:
      ports:
      - 443
      - 8443
      - 2053
      - 2083
      - 2087
      - 2096
proxies:
- name: 'Trojan #1'
  type: trojan
  server: 13.36.109.123
  port: 22222
  password: telegram-id-privatevpns
  network: tcp
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: trojan.burgerip.co.uk
  client-fingerprint: chrome
  alpn:
  - http/1.1
- name: 'Trojan #2'
  type: trojan
  server: 188.114.98.0
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.calmlunch.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.calmlunch.com
- name: 'Trojan #3'
  type: trojan
  server: 162.159.36.20
  port: 443
  password: 6202b230-417c-4d8e-b624-0f71afa9c75d
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: sni.111000.dynv6.net
  client-fingerprint: chrome
  alpn:
  - http/1.1
  ws-opts:
    path: /?proxyip=ip.111000.de5.net%3A443
    headers:
      Host: sni.111000.dynv6.net
- name: 'Trojan #4'
  type: trojan
  server: 172.64.146.129
  port: 443
  password: 6202b230-417c-4d8e-b624-0f71afa9c75d
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: sni.111000.dynv6.net
  client-fingerprint: chrome
  alpn:
  - http/1.1
  ws-opts:
    path: /?proxyip=ip.111000.de5.net%3A443
    headers:
      Host: sni.111000.dynv6.net
- name: 'Trojan #5'
  type: trojan
  server: 162.159.152.2
  port: 443
  password: 6202b230-417c-4d8e-b624-0f71afa9c75d
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: sni.111000.dynv6.net
  client-fingerprint: chrome
  alpn:
  - http/1.1
  ws-opts:
    path: /?proxyip=ip.111000.de5.net%3A443
    headers:
      Host: sni.111000.dynv6.net
- name: 'Trojan #6'
  type: trojan
  server: 50.7.4.243
  port: 443
  password: 8r%3C%5B9%27l6hAO%238ZQi
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: Koma-YT.PAGeS.Dev
  client-fingerprint: chrome
  ws-opts:
    path: /tr
    headers:
      Host: Koma-YT.PAGeS.Dev
- name: 'Trojan #7'
  type: trojan
  server: 8.6.112.0
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.multiplydose.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.multiplydose.com
- name: 'Trojan #8'
  type: trojan
  server: allnet-triss-aaa.gamelip.com
  port: 7080
  password: Jl03LDoDjF
  network: tcp
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: allnet7080-sa-aaaaccc-aaa.nexitie.com
  client-fingerprint: chrome
proxy-groups:
- name: Proxy Select
  type: select
  proxies:
  - Auto Select
  - 'Trojan #1'
  - 'Trojan #2'
  - 'Trojan #3'
  - 'Trojan #4'
  - 'Trojan #5'
  - 'Trojan #6'
  - 'Trojan #7'
  - 'Trojan #8'
  - DIRECT
- name: Auto Select
  type: url-test
  proxies:
  - 'Trojan #1'
  - 'Trojan #2'
  - 'Trojan #3'
  - 'Trojan #4'
  - 'Trojan #5'
  - 'Trojan #6'
  - 'Trojan #7'
  - 'Trojan #8'
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 150
  lazy: true
rules:
- DOMAIN-SUFFIX,net2025.afsharidempire.uk,DIRECT
- DOMAIN,cp.cloudflare.com,Auto Select
- DOMAIN-SUFFIX,cdn.ir,DIRECT
- DOMAIN-SUFFIX,aparat.com,DIRECT
- DOMAIN-SUFFIX,digikala.com,DIRECT
- DOMAIN-SUFFIX,divar.ir,DIRECT
- DOMAIN-SUFFIX,snapp.ir,DIRECT
- DOMAIN-SUFFIX,torob.com,DIRECT
- DOMAIN-SUFFIX,bamilo.com,DIRECT
- DOMAIN-SUFFIX,alibaba.ir,DIRECT
- DOMAIN-SUFFIX,ban.ir,DIRECT
- DOMAIN-KEYWORD,telegram,Auto Select
- DOMAIN-SUFFIX,t.me,Auto Select
- DOMAIN-SUFFIX,telegram.org,Auto Select
- DOMAIN-SUFFIX,google.com,Auto Select
- DOMAIN-SUFFIX,youtube.com,Auto Select
- DOMAIN-SUFFIX,github.com,Auto Select
- DOMAIN-SUFFIX,instagram.com,Auto Select
- DOMAIN-SUFFIX,twitter.com,Auto Select
- DOMAIN-SUFFIX,whatsapp.com,Auto Select
- GEOIP,IR,DIRECT
- MATCH,Proxy Select
ntp:
  enable: true
  server: time.cloudflare.com
  port: 123
  interval: 30
