mixed-port: 7890
ipv6: false
allow-lan: true
mode: rule
log-level: warning
unified-delay: false
tcp-concurrent: true
geo-auto-update: true
geo-update-interval: 168
external-controller: 127.0.0.1:9090
external-controller-cors:
  allow-origins:
  - '*'
  allow-private-network: true
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  respect-rules: true
  use-system-hosts: false
  listen: 0.0.0.0:1053
  ipv6: false
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
  proxy-server-nameserver:
  - 8.8.8.8
  direct-nameserver:
  - 8.8.8.8
  direct-nameserver-follow-policy: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - '*.localhost'
  - '*.ir'
  - '*.test'
  - '*.localdomain'
  - '*.home'
  - '*.internal'
tun:
  enable: true
  stack: gvisor
  auto-route: true
  strict-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
  mtu: 9000
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports:
      - 80
      - 8080
      - 8880
      - 2052
      - 2082
      - 2086
      - 2095
    TLS:
      ports:
      - 443
      - 8443
      - 2053
      - 2083
      - 2087
      - 2096
proxies:
- name: 'Trojan #1'
  type: trojan
  server: 193.151.152.206
  port: 40443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.ignitelimit.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.ignitelimit.com
- name: 'Trojan #2'
  type: trojan
  server: 85.198.9.204
  port: 40443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.ignitelimit.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.ignitelimit.com
- name: 'Trojan #3'
  type: trojan
  server: 104.19.229.21
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.multiplydose.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.multiplydose.com
- name: 'Trojan #4'
  type: trojan
  server: 95.38.163.199
  port: 40443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.ignitelimit.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.ignitelimit.com
- name: 'Trojan #5'
  type: trojan
  server: 188.121.105.201
  port: 40443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.ignitelimit.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.ignitelimit.com
- name: 'Trojan #6'
  type: trojan
  server: 193.151.152.73
  port: 40443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.ignitelimit.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.ignitelimit.com
- name: 'Trojan #7'
  type: trojan
  server: 193.151.145.252
  port: 40443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.ignitelimit.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.ignitelimit.com
- name: 'Trojan #8'
  type: trojan
  server: 95.38.165.189
  port: 40443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.ignitelimit.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.ignitelimit.com
- name: 'Trojan #9'
  type: trojan
  server: 37.32.9.230
  port: 40443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.ignitelimit.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.ignitelimit.com
- name: 'Trojan #10'
  type: trojan
  server: 37.32.11.121
  port: 40443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.ignitelimit.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.ignitelimit.com
- name: 'Trojan #11'
  type: trojan
  server: 85.198.20.177
  port: 40443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.ignitelimit.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.ignitelimit.com
- name: 'Trojan #12'
  type: trojan
  server: 104.19.229.21
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.multiplydose.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.multiplydose.com
- name: 'Trojan #13'
  type: trojan
  server: 46.149.78.144
  port: 8443
  password: 8r%3C%5B9%27l6hAO%238ZQi
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: Koma-YT.PAGeS.Dev
  client-fingerprint: chrome
  ws-opts:
    path: /trTelegram🇨🇳+@WangCai2
    headers:
      Host: Koma-YT.PAGeS.Dev
- name: 'Trojan #14'
  type: trojan
  server: 104.17.101.139
  port: 443
  password: 6202b230-417c-4d8e-b624-0f71afa9c75d
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: sni.111000.dynv6.net
  client-fingerprint: chrome
  alpn:
  - http/1.1
  ws-opts:
    path: /?proxyip=ip.111000.de5.net%3A443
    headers:
      Host: sni.111000.dynv6.net
- name: 'Trojan #15'
  type: trojan
  server: 37.152.186.182
  port: 40443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.ignitelimit.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.ignitelimit.com
- name: 'Trojan #16'
  type: trojan
  server: 2.144.7.232
  port: 40443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.creationlong.org
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.creationlong.org
- name: 'Trojan #17'
  type: trojan
  server: 2.144.6.200
  port: 40443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.creationlong.org
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.creationlong.org
- name: 'Trojan #18'
  type: trojan
  server: 2.144.23.174
  port: 40443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.creationlong.org
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.creationlong.org
- name: 'Trojan #19'
  type: trojan
  server: 2.144.22.122
  port: 40443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.creationlong.org
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.creationlong.org
- name: 'Trojan #20'
  type: trojan
  server: 2.144.7.80
  port: 40443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.ignitelimit.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.ignitelimit.com
- name: 'Trojan #21'
  type: trojan
  server: 2.144.20.221
  port: 40443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.ignitelimit.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.ignitelimit.com
- name: 'Trojan #22'
  type: trojan
  server: 2.144.23.72
  port: 40443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.ignitelimit.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.ignitelimit.com
- name: 'Trojan #23'
  type: trojan
  server: 94.101.177.118
  port: 40443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.ignitelimit.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.ignitelimit.com
- name: 'Trojan #24'
  type: trojan
  server: 2.144.15.40
  port: 40443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.ignitelimit.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.ignitelimit.com
- name: 'Trojan #25'
  type: trojan
  server: 2.144.15.100
  port: 40443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.creationlong.org
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.creationlong.org
- name: 'Trojan #26'
  type: trojan
  server: 2.144.20.16
  port: 40443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.creationlong.org
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.creationlong.org
- name: 'Trojan #27'
  type: trojan
  server: 2.144.22.10
  port: 40443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.creationlong.org
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.creationlong.org
- name: 'Trojan #28'
  type: trojan
  server: 95.38.162.35
  port: 40443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.ignitelimit.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.ignitelimit.com
- name: 'Trojan #29'
  type: trojan
  server: 104.19.229.21
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.creationlong.org
  client-fingerprint: safari
  ws-opts:
    path: /assignment
    headers:
      Host: www.creationlong.org
- name: 'Trojan #31'
  type: trojan
  server: 2.144.6.222
  port: 40443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.ignitelimit.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.ignitelimit.com
- name: 'Trojan #32'
  type: trojan
  server: 104.19.229.21
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.creationlong.org
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.creationlong.org
- name: 'Trojan #33'
  type: trojan
  server: sourceforge.net
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.calmloud.com
  client-fingerprint: chrome
  alpn:
  - http/1.1
  ws-opts:
    path: /assignment
    headers:
      Host: www.calmloud.com
- name: 'Trojan #34'
  type: trojan
  server: 80.74.28.213
  port: 8443
  password: 8r%3C%5B9%27l6hAO%238ZQi
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: Koma-YT.PAGeS.Dev
  client-fingerprint: chrome
  ws-opts:
    path: /trTelegram🇨🇳+@WangCai2
    headers:
      Host: Koma-YT.PAGeS.Dev
- name: 'Trojan #35'
  type: trojan
  server: 162.159.36.20
  port: 443
  password: 6202b230-417c-4d8e-b624-0f71afa9c75d
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: sni.111000.dynv6.net
  client-fingerprint: chrome
  alpn:
  - http/1.1
  ws-opts:
    path: /?proxyip=ip.111000.de5.net:443
    headers:
      Host: sni.111000.dynv6.net
- name: 'Trojan #36'
  type: trojan
  server: sourceforge.net
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.calmloud.com
  client-fingerprint: chrome
  alpn:
  - http/1.1
  ws-opts:
    path: /assignment
    headers:
      Host: www.calmloud.com
- name: 'Trojan #37'
  type: trojan
  server: 104.19.229.21
  port: 443
  password: humanity
  network: ws
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: www.multiplydose.com
  client-fingerprint: chrome
  ws-opts:
    path: /assignment
    headers:
      Host: www.multiplydose.com
- name: 'Trojan #38'
  type: trojan
  server: 51.102.92.172
  port: 22222
  password: telegram-id-privatevpns
  network: tcp
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: trojan.burgerip.co.uk
  client-fingerprint: chrome
  alpn:
  - http/1.1
proxy-groups:
- name: Proxy Select
  type: select
  proxies:
  - Auto Select
  - 'Trojan #1'
  - 'Trojan #2'
  - 'Trojan #3'
  - 'Trojan #4'
  - 'Trojan #5'
  - 'Trojan #6'
  - 'Trojan #7'
  - 'Trojan #8'
  - 'Trojan #9'
  - 'Trojan #10'
  - 'Trojan #11'
  - 'Trojan #12'
  - 'Trojan #13'
  - 'Trojan #14'
  - 'Trojan #15'
  - 'Trojan #16'
  - 'Trojan #17'
  - 'Trojan #18'
  - 'Trojan #19'
  - 'Trojan #20'
  - 'Trojan #21'
  - 'Trojan #22'
  - 'Trojan #23'
  - 'Trojan #24'
  - 'Trojan #25'
  - 'Trojan #26'
  - 'Trojan #27'
  - 'Trojan #28'
  - 'Trojan #29'
  - 'Trojan #31'
  - 'Trojan #32'
  - 'Trojan #33'
  - 'Trojan #34'
  - 'Trojan #35'
  - 'Trojan #36'
  - 'Trojan #37'
  - 'Trojan #38'
  - DIRECT
- name: Auto Select
  type: url-test
  proxies:
  - 'Trojan #1'
  - 'Trojan #2'
  - 'Trojan #3'
  - 'Trojan #4'
  - 'Trojan #5'
  - 'Trojan #6'
  - 'Trojan #7'
  - 'Trojan #8'
  - 'Trojan #9'
  - 'Trojan #10'
  - 'Trojan #11'
  - 'Trojan #12'
  - 'Trojan #13'
  - 'Trojan #14'
  - 'Trojan #15'
  - 'Trojan #16'
  - 'Trojan #17'
  - 'Trojan #18'
  - 'Trojan #19'
  - 'Trojan #20'
  - 'Trojan #21'
  - 'Trojan #22'
  - 'Trojan #23'
  - 'Trojan #24'
  - 'Trojan #25'
  - 'Trojan #26'
  - 'Trojan #27'
  - 'Trojan #28'
  - 'Trojan #29'
  - 'Trojan #31'
  - 'Trojan #32'
  - 'Trojan #33'
  - 'Trojan #34'
  - 'Trojan #35'
  - 'Trojan #36'
  - 'Trojan #37'
  - 'Trojan #38'
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 150
  lazy: true
rules:
- DOMAIN-SUFFIX,net2025.afsharidempire.uk,DIRECT
- DOMAIN,cp.cloudflare.com,Auto Select
- DOMAIN-SUFFIX,cdn.ir,DIRECT
- DOMAIN-SUFFIX,aparat.com,DIRECT
- DOMAIN-SUFFIX,digikala.com,DIRECT
- DOMAIN-SUFFIX,divar.ir,DIRECT
- DOMAIN-SUFFIX,snapp.ir,DIRECT
- DOMAIN-SUFFIX,torob.com,DIRECT
- DOMAIN-SUFFIX,bamilo.com,DIRECT
- DOMAIN-SUFFIX,alibaba.ir,DIRECT
- DOMAIN-SUFFIX,ban.ir,DIRECT
- DOMAIN-KEYWORD,telegram,Auto Select
- DOMAIN-SUFFIX,t.me,Auto Select
- DOMAIN-SUFFIX,telegram.org,Auto Select
- DOMAIN-SUFFIX,google.com,Auto Select
- DOMAIN-SUFFIX,youtube.com,Auto Select
- DOMAIN-SUFFIX,github.com,Auto Select
- DOMAIN-SUFFIX,instagram.com,Auto Select
- DOMAIN-SUFFIX,twitter.com,Auto Select
- DOMAIN-SUFFIX,whatsapp.com,Auto Select
- GEOIP,IR,DIRECT
- MATCH,Proxy Select
ntp:
  enable: true
  server: time.cloudflare.com
  port: 123
  interval: 30
