mixed-port: 7890
ipv6: false
allow-lan: true
mode: rule
log-level: warning
unified-delay: false
tcp-concurrent: true
geo-auto-update: true
geo-update-interval: 168
external-controller: 127.0.0.1:9090
external-controller-cors:
  allow-origins:
  - '*'
  allow-private-network: true
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  respect-rules: true
  use-system-hosts: false
  listen: 0.0.0.0:1053
  ipv6: false
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
  proxy-server-nameserver:
  - 8.8.8.8
  direct-nameserver:
  - 8.8.8.8
  direct-nameserver-follow-policy: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - '*.localhost'
  - '*.ir'
  - '*.test'
  - '*.localdomain'
  - '*.home'
  - '*.internal'
tun:
  enable: true
  stack: gvisor
  auto-route: true
  strict-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
  mtu: 9000
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports:
      - 80
      - 8080
      - 8880
      - 2052
      - 2082
      - 2086
      - 2095
    TLS:
      ports:
      - 443
      - 8443
      - 2053
      - 2083
      - 2087
      - 2096
proxies:
- name: 'ARISTA #1'
  type: vmess
  server: ak.reata.ir
  port: 16482
  uuid: 3d322eba-f7b8-4a84-bdeb-fcce9286351c
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: ak.reata.ir
  client-fingerprint: ''
- name: 'ARISTA #2'
  type: vmess
  server: ak.reata.ir
  port: 16482
  uuid: 3d322eba-f7b8-4a84-bdeb-fcce9286351c
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: ak.reata.ir
  client-fingerprint: ''
- name: 'ARISTA #3'
  type: vmess
  server: b51d64cb-c5d6-4791-8ecf-0a6d8d71c717.wtf
  port: 22001
  uuid: 7b170952-8a7b-4638-94f4-f7737154afe3
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: b51d64cb-c5d6-4791-8ecf-0a6d8d71c717.wtf
  client-fingerprint: ''
- name: 'ARISTA #4'
  type: vmess
  server: network.spacestar.best
  port: 2082
  uuid: f243d3f8-77ae-4c0d-add9-c82e32172b74
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: januray.helxx.ir
  client-fingerprint: ''
  ws-opts:
    path: /newserver
    headers:
      Host: januray.helxx.ir
- name: 'ARISTA #5'
  type: vmess
  server: b51d64cb-c5d6-4791-8ecf-0a6d8d71c717.wtf
  port: 21930
  uuid: 97132b07-c50d-48f1-a569-ef6b2d792097
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: b51d64cb-c5d6-4791-8ecf-0a6d8d71c717.wtf
  client-fingerprint: ''
- name: 'ARISTA #6'
  type: vmess
  server: b51d64cb-c5d6-4791-8ecf-0a6d8d71c717.wtf
  port: 21930
  uuid: f164594a-4e06-47df-9264-07fcd7f0acf1
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: b51d64cb-c5d6-4791-8ecf-0a6d8d71c717.wtf
  client-fingerprint: ''
- name: 'ARISTA #7'
  type: vmess
  server: b51d64cb-c5d6-4791-8ecf-0a6d8d71c717.wtf
  port: 21953
  uuid: 5710fd2a-5256-498e-963a-6a7b6949bccd
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: b51d64cb-c5d6-4791-8ecf-0a6d8d71c717.wtf
  client-fingerprint: ''
- name: 'ARISTA #8'
  type: vmess
  server: b51d64cb-c5d6-4791-8ecf-0a6d8d71c717.wtf
  port: 21958
  uuid: 39d6990b-f757-4703-a7f9-df266505b63d
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: b51d64cb-c5d6-4791-8ecf-0a6d8d71c717.wtf
  client-fingerprint: ''
proxy-groups:
- name: Proxy Select
  type: select
  proxies:
  - Auto Select
  - 'ARISTA #1'
  - 'ARISTA #2'
  - 'ARISTA #3'
  - 'ARISTA #4'
  - 'ARISTA #5'
  - 'ARISTA #6'
  - 'ARISTA #7'
  - 'ARISTA #8'
  - DIRECT
- name: Auto Select
  type: url-test
  proxies:
  - 'ARISTA #1'
  - 'ARISTA #2'
  - 'ARISTA #3'
  - 'ARISTA #4'
  - 'ARISTA #5'
  - 'ARISTA #6'
  - 'ARISTA #7'
  - 'ARISTA #8'
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 150
  lazy: true
rules:
- DOMAIN-SUFFIX,net2025.afsharidempire.uk,DIRECT
- DOMAIN,cp.cloudflare.com,Auto Select
- DOMAIN-SUFFIX,cdn.ir,DIRECT
- DOMAIN-SUFFIX,aparat.com,DIRECT
- DOMAIN-SUFFIX,digikala.com,DIRECT
- DOMAIN-SUFFIX,divar.ir,DIRECT
- DOMAIN-SUFFIX,snapp.ir,DIRECT
- DOMAIN-SUFFIX,torob.com,DIRECT
- DOMAIN-SUFFIX,bamilo.com,DIRECT
- DOMAIN-SUFFIX,alibaba.ir,DIRECT
- DOMAIN-SUFFIX,ban.ir,DIRECT
- DOMAIN-KEYWORD,telegram,Auto Select
- DOMAIN-SUFFIX,t.me,Auto Select
- DOMAIN-SUFFIX,telegram.org,Auto Select
- DOMAIN-SUFFIX,google.com,Auto Select
- DOMAIN-SUFFIX,youtube.com,Auto Select
- DOMAIN-SUFFIX,github.com,Auto Select
- DOMAIN-SUFFIX,instagram.com,Auto Select
- DOMAIN-SUFFIX,twitter.com,Auto Select
- DOMAIN-SUFFIX,whatsapp.com,Auto Select
- GEOIP,IR,DIRECT
- MATCH,Proxy Select
ntp:
  enable: true
  server: time.cloudflare.com
  port: 123
  interval: 30
