mixed-port: 7890
ipv6: false
allow-lan: true
mode: rule
log-level: warning
unified-delay: false
tcp-concurrent: true
geo-auto-update: true
geo-update-interval: 168
external-controller: 127.0.0.1:9090
external-controller-cors:
  allow-origins:
  - '*'
  allow-private-network: true
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  respect-rules: true
  use-system-hosts: false
  listen: 0.0.0.0:1053
  ipv6: false
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
  proxy-server-nameserver:
  - 8.8.8.8
  direct-nameserver:
  - 8.8.8.8
  direct-nameserver-follow-policy: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - '*.localhost'
  - '*.ir'
  - '*.test'
  - '*.localdomain'
  - '*.home'
  - '*.internal'
tun:
  enable: true
  stack: gvisor
  auto-route: true
  strict-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
  mtu: 9000
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports:
      - 80
      - 8080
      - 8880
      - 2052
      - 2082
      - 2086
      - 2095
    TLS:
      ports:
      - 443
      - 8443
      - 2053
      - 2083
      - 2087
      - 2096
proxies:
- name: 'ARISTA #1'
  type: vmess
  server: 193.151.131.118
  port: 22901
  uuid: 0c46f160-d048-4ed8-a247-d66643b3197c
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 193.151.131.118
  client-fingerprint: ''
- name: 'ARISTA #2'
  type: vmess
  server: b51d64cb-c5d6-4791-8ecf-0a6d8d71c717.wtf
  port: 22903
  uuid: 14cab9ec-8a1a-44d9-b2c9-0c5ee8ce3a8c
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: b51d64cb-c5d6-4791-8ecf-0a6d8d71c717.wtf
  client-fingerprint: ''
- name: 'ARISTA #3'
  type: vmess
  server: b51d64cb-c5d6-4791-8ecf-0a6d8d71c717.wtf
  port: 22911
  uuid: 638dea38-eb02-4fac-99aa-f83453606467
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: b51d64cb-c5d6-4791-8ecf-0a6d8d71c717.wtf
  client-fingerprint: ''
- name: 'ARISTA #4'
  type: vmess
  server: dn.torontomovie.com
  port: 8080
  uuid: 001ed66a-c019-486d-8110-0765cbf0c31d
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: dn.torontomovie.com
  client-fingerprint: ''
- name: 'ARISTA #5'
  type: vmess
  server: 193.151.131.118
  port: 22911
  uuid: 638dea38-eb02-4fac-99aa-f83453606467
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 193.151.131.118
  client-fingerprint: ''
- name: 'ARISTA #6'
  type: vmess
  server: 87.107.81.215
  port: 8080
  uuid: 001ed66a-c019-486d-8110-0765cbf0c31d
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 87.107.81.215
  client-fingerprint: ''
- name: 'ARISTA #7'
  type: vmess
  server: 85.90.217.42
  port: 22324
  uuid: 04621bae-ab36-11ec-b909-0242ac120002
  alterId: 0
  cipher: null
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 85.90.217.42
  client-fingerprint: null
- name: 'ARISTA #8'
  type: vmess
  server: 27.122.57.43
  port: 11638
  uuid: 0be3a336-85ad-4c42-930b-05318236e68c
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 27.122.57.43
  client-fingerprint: chrome
proxy-groups:
- name: Proxy Select
  type: select
  proxies:
  - Auto Select
  - 'ARISTA #1'
  - 'ARISTA #2'
  - 'ARISTA #3'
  - 'ARISTA #4'
  - 'ARISTA #5'
  - 'ARISTA #6'
  - 'ARISTA #7'
  - 'ARISTA #8'
  - DIRECT
- name: Auto Select
  type: url-test
  proxies:
  - 'ARISTA #1'
  - 'ARISTA #2'
  - 'ARISTA #3'
  - 'ARISTA #4'
  - 'ARISTA #5'
  - 'ARISTA #6'
  - 'ARISTA #7'
  - 'ARISTA #8'
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 150
  lazy: true
rules:
- DOMAIN-SUFFIX,net2025.afsharidempire.uk,DIRECT
- DOMAIN,cp.cloudflare.com,Auto Select
- DOMAIN-SUFFIX,cdn.ir,DIRECT
- DOMAIN-SUFFIX,aparat.com,DIRECT
- DOMAIN-SUFFIX,digikala.com,DIRECT
- DOMAIN-SUFFIX,divar.ir,DIRECT
- DOMAIN-SUFFIX,snapp.ir,DIRECT
- DOMAIN-SUFFIX,torob.com,DIRECT
- DOMAIN-SUFFIX,bamilo.com,DIRECT
- DOMAIN-SUFFIX,alibaba.ir,DIRECT
- DOMAIN-SUFFIX,ban.ir,DIRECT
- DOMAIN-KEYWORD,telegram,Auto Select
- DOMAIN-SUFFIX,t.me,Auto Select
- DOMAIN-SUFFIX,telegram.org,Auto Select
- DOMAIN-SUFFIX,google.com,Auto Select
- DOMAIN-SUFFIX,youtube.com,Auto Select
- DOMAIN-SUFFIX,github.com,Auto Select
- DOMAIN-SUFFIX,instagram.com,Auto Select
- DOMAIN-SUFFIX,twitter.com,Auto Select
- DOMAIN-SUFFIX,whatsapp.com,Auto Select
- GEOIP,IR,DIRECT
- MATCH,Proxy Select
ntp:
  enable: true
  server: time.cloudflare.com
  port: 123
  interval: 30
