mixed-port: 7890
ipv6: false
allow-lan: true
mode: rule
log-level: warning
unified-delay: false
tcp-concurrent: true
geo-auto-update: true
geo-update-interval: 168
external-controller: 127.0.0.1:9090
external-controller-cors:
  allow-origins:
  - '*'
  allow-private-network: true
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  respect-rules: true
  use-system-hosts: false
  listen: 0.0.0.0:1053
  ipv6: false
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
  proxy-server-nameserver:
  - 8.8.8.8
  direct-nameserver:
  - 8.8.8.8
  direct-nameserver-follow-policy: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - '*.localhost'
  - '*.ir'
  - '*.test'
  - '*.localdomain'
  - '*.home'
  - '*.internal'
tun:
  enable: true
  stack: gvisor
  auto-route: true
  strict-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
  mtu: 9000
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports:
      - 80
      - 8080
      - 8880
      - 2052
      - 2082
      - 2086
      - 2095
    TLS:
      ports:
      - 443
      - 8443
      - 2053
      - 2083
      - 2087
      - 2096
proxies:
- name: 'ARISTA #1'
  type: vmess
  server: uk.connfull.org
  port: 2053
  uuid: d64d52b1-144f-4bce-a6d7-1324de187b1b
  alterId: 0
  cipher: auto
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: uk.connfull.org
  client-fingerprint: chrome
  alpn:
  - http/1.1
- name: 'ARISTA #2'
  type: vmess
  server: spt.reata.ir
  port: 1020
  uuid: a8022edb-0bd7-4f86-b70d-20f7f8a59814
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: spt.reata.ir
  client-fingerprint: ''
- name: 'ARISTA #3'
  type: vmess
  server: uk.connfull.org
  port: 2053
  uuid: d64d52b1-144f-4bce-a6d7-1324de187b1b
  alterId: 0
  cipher: auto
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: uk.connfull.org
  client-fingerprint: chrome
  alpn:
  - http/1.1
- name: 'ARISTA #4'
  type: vmess
  server: 95.179.169.64
  port: 59171
  uuid: aa36638a-88c9-45a3-8144-ffb6d8a7f8ea
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 95.179.169.64
  client-fingerprint: ''
- name: 'ARISTA #5'
  type: vmess
  server: it.connfull.org
  port: 2053
  uuid: 79e33f2e-6f88-4867-b311-844198e59270
  alterId: 0
  cipher: auto
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: it.connfull.org
  client-fingerprint: chrome
- name: 'ARISTA #6'
  type: vmess
  server: ro.connfull.org
  port: 2053
  uuid: 9a6be41d-511a-4800-b828-368ca32dd56d
  alterId: 0
  cipher: auto
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: ro.connfull.org
  client-fingerprint: chrome
- name: 'ARISTA #7'
  type: vmess
  server: 51.195.235.71
  port: 2052
  uuid: 59e28f78-c31b-4613-9d9f-1e6732a31f46
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 51.195.235.71
  client-fingerprint: ''
- name: 'ARISTA #8'
  type: vmess
  server: azmononline.konkuriran.sbs
  port: 2080
  uuid: cd682302-c9d7-4c0d-bada-52e7d652c22c
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: azmononline.konkuriran.sbs
  client-fingerprint: ''
- name: 'ARISTA #9'
  type: vmess
  server: 61.245.11.60
  port: 80
  uuid: a3e3a710-79f8-4ae0-b83c-607aab40d197
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 61.245.11.60
  client-fingerprint: ''
  ws-opts:
    path: /vmess/
    headers:
      Host: 61.245.11.60
- name: 'ARISTA #10'
  type: vmess
  server: 51.83.197.140
  port: 80
  uuid: 7d8c2904-0917-4002-bff9-9a44e1c92fb1
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 51.83.197.140
  client-fingerprint: ''
  ws-opts:
    path: /api/v1
    headers:
      Host: 51.83.197.140
- name: 'ARISTA #11'
  type: vmess
  server: node-de.connectsuite.org
  port: 2053
  uuid: fd169a0a-5c32-4f3e-9b6c-28dd35f2a5e5
  alterId: 0
  cipher: auto
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: node-de.connectsuite.org
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
- name: 'ARISTA #12'
  type: vmess
  server: uk.connfull.org
  port: 2053
  uuid: d64d52b1-144f-4bce-a6d7-1324de187b1b
  alterId: 0
  cipher: auto
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: uk.connfull.org
  client-fingerprint: chrome
- name: 'ARISTA #13'
  type: vmess
  server: pl.connfull.org
  port: 2053
  uuid: d8a706d0-9f21-46b8-9c08-f826b7799c77
  alterId: 0
  cipher: auto
  network: raw
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: pl.connfull.org
  client-fingerprint: chrome
- name: 'ARISTA #14'
  type: vmess
  server: 108.61.190.45
  port: 36956
  uuid: 8b8db685-af04-4053-9452-a12fd98c8db1
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 108.61.190.45
  client-fingerprint: ''
- name: 'ARISTA #15'
  type: vmess
  server: 51.195.235.71
  port: 2052
  uuid: 59e28f78-c31b-4613-9d9f-1e6732a31f46
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 51.195.235.71
  client-fingerprint: ''
- name: 'ARISTA #16'
  type: vmess
  server: 95.179.169.64
  port: 59171
  uuid: 511156b4-6d50-438c-bb46-95c553635874
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 95.179.169.64
  client-fingerprint: ''
- name: 'ARISTA #17'
  type: vmess
  server: 212.87.198.79
  port: 45255
  uuid: dd5ffd23-cef5-44dd-a143-658bd7f3943a
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: bale.ai
  client-fingerprint: ''
- name: 'ARISTA #18'
  type: vmess
  server: pro.45259.net
  port: 48668
  uuid: b783cb91-3a94-468c-8aac-0bf99c8a06e0
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: pro.45259.net
  client-fingerprint: ''
- name: 'ARISTA #19'
  type: vmess
  server: uk.connfull.org
  port: 2053
  uuid: d64d52b1-144f-4bce-a6d7-1324de187b1b
  alterId: 0
  cipher: auto
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: uk.connfull.org
  client-fingerprint: chrome
  alpn:
  - http/1.1
- name: 'ARISTA #20'
  type: vmess
  server: 45.128.72.44
  port: 80
  uuid: a2170d39-140a-47f9-85b8-084078856c36
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 45.128.72.44
  client-fingerprint: ''
  ws-opts:
    path: /api/v1
    headers:
      Host: 45.128.72.44
- name: 'ARISTA #21'
  type: vmess
  server: usaapp1.jisuyun.top
  port: 2053
  uuid: 4b80aa86-4354-40bb-d2a3-47126cff0bea
  alterId: 0
  cipher: auto
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: usaapp1.jisuyun.top
  client-fingerprint: ''
  ws-opts:
    path: /usavm
    headers:
      Host: usaapp1.jisuyun.top
- name: 'ARISTA #22'
  type: vmess
  server: 212.87.198.79
  port: 45255
  uuid: dd5ffd23-cef5-44dd-a143-658bd7f3943a
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: bale.ai
  client-fingerprint: ''
- name: 'ARISTA #23'
  type: vmess
  server: 95.179.169.64
  port: 59171
  uuid: aa36638a-88c9-45a3-8144-ffb6d8a7f8ea
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 95.179.169.64
  client-fingerprint: ''
- name: 'ARISTA #24'
  type: vmess
  server: 95.179.169.64
  port: 59171
  uuid: 511156b4-6d50-438c-bb46-95c553635874
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 95.179.169.64
  client-fingerprint: ''
proxy-groups:
- name: Proxy Select
  type: select
  proxies:
  - Auto Select
  - 'ARISTA #1'
  - 'ARISTA #2'
  - 'ARISTA #3'
  - 'ARISTA #4'
  - 'ARISTA #5'
  - 'ARISTA #6'
  - 'ARISTA #7'
  - 'ARISTA #8'
  - 'ARISTA #9'
  - 'ARISTA #10'
  - 'ARISTA #11'
  - 'ARISTA #12'
  - 'ARISTA #13'
  - 'ARISTA #14'
  - 'ARISTA #15'
  - 'ARISTA #16'
  - 'ARISTA #17'
  - 'ARISTA #18'
  - 'ARISTA #19'
  - 'ARISTA #20'
  - 'ARISTA #21'
  - 'ARISTA #22'
  - 'ARISTA #23'
  - 'ARISTA #24'
  - DIRECT
- name: Auto Select
  type: url-test
  proxies:
  - 'ARISTA #1'
  - 'ARISTA #2'
  - 'ARISTA #3'
  - 'ARISTA #4'
  - 'ARISTA #5'
  - 'ARISTA #6'
  - 'ARISTA #7'
  - 'ARISTA #8'
  - 'ARISTA #9'
  - 'ARISTA #10'
  - 'ARISTA #11'
  - 'ARISTA #12'
  - 'ARISTA #13'
  - 'ARISTA #14'
  - 'ARISTA #15'
  - 'ARISTA #16'
  - 'ARISTA #17'
  - 'ARISTA #18'
  - 'ARISTA #19'
  - 'ARISTA #20'
  - 'ARISTA #21'
  - 'ARISTA #22'
  - 'ARISTA #23'
  - 'ARISTA #24'
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 150
  lazy: true
rules:
- DOMAIN-SUFFIX,net2025.afsharidempire.uk,DIRECT
- DOMAIN,cp.cloudflare.com,Auto Select
- DOMAIN-SUFFIX,cdn.ir,DIRECT
- DOMAIN-SUFFIX,aparat.com,DIRECT
- DOMAIN-SUFFIX,digikala.com,DIRECT
- DOMAIN-SUFFIX,divar.ir,DIRECT
- DOMAIN-SUFFIX,snapp.ir,DIRECT
- DOMAIN-SUFFIX,torob.com,DIRECT
- DOMAIN-SUFFIX,bamilo.com,DIRECT
- DOMAIN-SUFFIX,alibaba.ir,DIRECT
- DOMAIN-SUFFIX,ban.ir,DIRECT
- DOMAIN-KEYWORD,telegram,Auto Select
- DOMAIN-SUFFIX,t.me,Auto Select
- DOMAIN-SUFFIX,telegram.org,Auto Select
- DOMAIN-SUFFIX,google.com,Auto Select
- DOMAIN-SUFFIX,youtube.com,Auto Select
- DOMAIN-SUFFIX,github.com,Auto Select
- DOMAIN-SUFFIX,instagram.com,Auto Select
- DOMAIN-SUFFIX,twitter.com,Auto Select
- DOMAIN-SUFFIX,whatsapp.com,Auto Select
- GEOIP,IR,DIRECT
- MATCH,Proxy Select
ntp:
  enable: true
  server: time.cloudflare.com
  port: 123
  interval: 30
